package hat

import (
	"net/http"
)

// ResponseAssertion asserts a quality of the response.
type ResponseAssertion func(r Response)

// CombineResponseAssertions returns a new ResponseAssertion which internally
// calls each member of asserts in the provided order.
func CombineResponseAssertions(asserts ...ResponseAssertion) ResponseAssertion {
	return func(r Response) {
		for _, a := range asserts {
			a(r)
		}
	}
}

// Response represents an HTTP response generated by hat.Request.
type Response struct {
	*http.Response

	createRequest func() *http.Request
}

// Assert runs each assertion against the response.
// It closes the response body after all of the assertions have ran.
func (r Response) Assert(assertions ...ResponseAssertion) Response {
	defer r.Body.Close()
	for _, a := range assertions {
		a(r)
	}
	return r
}

// Again applies opts to the request that created this response,
// then sends it again.
// It returns a completely new response.
// If Again is chained, all of the request options in the chain will be applied.
// If multiple Agains are called off of a single parent response, only the options
// from the leaf and the parent will be applied.
func (r Response) Again(t T, opts ...RequestOption) Response {
	return t.sendRequest(func() *http.Request {
		req := r.createRequest()
		for _, o := range opts {
			o(req)
		}
		return req
	})
}
